name: 'Run Tests'
description: 'Starts Emulator, Appium server, and triggers TestNG'
inputs:
  headless:
    description: 'Run headless'
    required: true

runs:
  using: "composite"
  steps:
    - name: Start Appium Server
      shell: powershell
      run: |
        Start-Process -FilePath "appium" -NoNewWindow
        Start-Sleep -Seconds 10 # Allow server time to bind to port 4723

    - name: Start Local Android Emulator
      shell: powershell
      run: |
        $emulatorArgs = "-avd Pixel_API_35 -verbose"
        
        # Append headless flag dynamically
        if ('${{ inputs.headless }}' -eq 'true') {
          $emulatorArgs += " -no-window"
        }
        
        Write-Host "Starting Emulator with args: $emulatorArgs"
        Start-Process -FilePath "C:\Android\emulator\emulator.exe" -ArgumentList $emulatorArgs -NoNewWindow
        
        Write-Host "Waiting for device to connect..."
        & adb wait-for-device
        
        Write-Host "Waiting for Android to finish booting..."
        while ((& adb shell getprop sys.boot_completed) -notmatch '1') { 
          Start-Sleep -Seconds 5 
        }
        Write-Host "Emulator is fully booted and ready!"

    - name: Run Maven TestNG Suite
      shell: bash
      run: mvn clean test -DsuiteXmlFile=testng.xml
